import { PropertyTemplate } from "../types/category.types";

const currencyEnums = ["NGN"];

// --------------------
// Color Enum
// --------------------
const colorPropertyObj: PropertyTemplate = {
  name: "Color",
  type: "enum",
  required: true,
  filterable: true,
  order: 1,
  enumValues: [
    { label: "Black", value: "black", hex: "#000000" },
    { label: "White", value: "white", hex: "#FFFFFF" },
    { label: "Red", value: "red", hex: "#FF0000" },
    { label: "Burgundy", value: "burgundy", hex: "#800020" },
    { label: "Blue", value: "blue", hex: "#0000FF" },
    { label: "Green", value: "green", hex: "#008000" },
    { label: "Yellow", value: "yellow", hex: "#FFFF00" },
    { label: "Pink", value: "pink", hex: "#FFC0CB" },
    { label: "Purple", value: "purple", hex: "#800080" },
    { label: "Orange", value: "orange", hex: "#FFA500" },
    { label: "Brown", value: "brown", hex: "#A52A2A" },
    { label: "Grey", value: "grey", hex: "#808080" },
    { label: "Beige", value: "beige", hex: "#F5F5DC" },
    { label: "Navy", value: "navy", hex: "#000080" },
    { label: "Teal", value: "teal", hex: "#008080" },
    { label: "Turquoise", value: "turquoise", hex: "#40E0D0" },
    { label: "Mint", value: "mint", hex: "#98FF98" },
    { label: "Lime", value: "lime", hex: "#00FF00" },
    { label: "Olive", value: "olive", hex: "#808000" },
    { label: "Khaki", value: "khaki", hex: "#F0E68C" },
    { label: "Gold", value: "gold", hex: "#FFD700" },
    { label: "Silver", value: "silver", hex: "#C0C0C0" },
    { label: "Bronze", value: "bronze", hex: "#CD7F32" },
    { label: "Copper", value: "copper", hex: "#B87333" },
    { label: "Rose Gold", value: "rose_gold", hex: "#B76E79" },
    { label: "Metallic", value: "metallic", hex: "#D3AF37" },
    { label: "Neon", value: "neon", hex: "#39FF14" },
    { label: "Pastel", value: "pastel", hex: "#FF6961" },
    {
      label: "Multicolor",
      value: "multicolor",
      background:
        "radial-gradient(circle, hsla(41, 83%, 70%, 1) 23%, hsla(321, 90%, 70%, 1) 100%)",
    },
    { label: "Lilac", value: "lilac", hex: "#C8A2C8" },
    { label: "Tan", value: "tan", hex: "#D2B48C" },
    { label: "Wine", value: "wine", hex: "#722F37" },
    { label: "Chocolate", value: "chocolate", hex: "#D2691E" },
    { label: "Milk", value: "milk", hex: "#F5F5DC" },
  ],
};
const colorEnums = colorPropertyObj.enumValues!.map((option) => option.value);

// --------------------
// Condition Enum
// --------------------

const conditionPropertyObject: PropertyTemplate = {
  name: "Condition",
  type: "enum",
  required: true,
  filterable: true,
  order: 2,
  enumValues: [
    {
      label: "New with tags",
      value: "New_with_tags",
      description: "Brand new item, never worn, with original tags attached",
    },
    {
      label: "New without tags",
      value: "New_without_tags",
      description:
        "Brand new item, never worn, original tags removed or missing",
    },
    {
      label: "Very Good",
      value: "Very_good",
      description:
        "Gently used item with minimal signs of wear; looks almost new",
    },
    {
      label: "Good",
      value: "Good",
      description:
        "Used item in good condition with minor wear or imperfections",
    },
    {
      label: "Satisfactory",
      value: "Satisfactory",
      description: "Used item with noticeable signs of wear; still functional",
    },
    {
      label: "Not fully functional",
      value: "Not_fully_functional",
      description:
        "Item is not fully functional or has damage; may require repair or use for parts",
    },
  ],
};
const conditionEnumValues = conditionPropertyObject.enumValues!.map(
  (option) => option.value,
);

// --------------------
// Pattern Property
// --------------------
const PatternProperty: PropertyTemplate = {
  name: "Pattern",
  type: "enum",
  required: false,
  filterable: true,
  order: 3,
  enumValues: [
    { label: "Solid", value: "solid" },
    { label: "Striped", value: "striped" },
    { label: "Checked", value: "checked" },
    { label: "Plaid", value: "plaid" },
    { label: "Polka Dot", value: "polka_dot" },
    { label: "Floral", value: "floral" },
    { label: "Graphic", value: "graphic" },
    { label: "Other", value: "other" },
  ],
};
const patternEnums = PatternProperty.enumValues!.map((option) => option.value);

// --------------------
// Material Property
// --------------------
const MaterialProperty: PropertyTemplate = {
  name: "Material",
  type: "enum",
  required: false,
  filterable: true,
  order: 4,
  enumValues: [
    { label: "Cotton", value: "cotton" },
    { label: "Polyester", value: "polyester" },
    { label: "Wool", value: "wool" },
    { label: "Leather", value: "leather" },
    { label: "Silk", value: "silk" },
    { label: "Denim", value: "denim" },
    { label: "Linen", value: "linen" },
    { label: "Synthetic", value: "synthetic" },
    { label: "Nylon", value: "nylon" },
    { label: "Spandex", value: "spandex" },
    { label: "Rayon", value: "rayon" },
    { label: "Lace", value: "lace" },
    { label: "Gold", value: "gold" },
    { label: "Silver", value: "silver" },
    { label: "Plastic", value: "plastic" },
    { label: "Wood", value: "wood" },
    { label: "Bronze", value: "bronze" },
    { label: "Metal", value: "metal" },
    { label: "Glass", value: "glass" },
    { label: "Ceramic", value: "ceramic" },
    { label: "Rubber", value: "rubber" },
    { label: "Silicone", value: "silicone" },
    { label: "Porcelain", value: "porcelain" },
    { label: "Other", value: "other" },
  ],
};
const materialEnums = MaterialProperty.enumValues!.map(
  (option) => option.value,
);

const accessorySizeEnums = [
  "standard",
  "oversized",
  "mini",
  "micro_mini",
  "large",
  "one_size",
  "adjustable",
  "other",
];
// --------------------
// Shoe Sizes
// --------------------
const shoeSizes: string[] = [
  // US sizes
  "US 4",
  "US 4.5",
  "US 5",
  "US 5.5",
  "US 6",
  "US 6.5",
  "US 7",
  "US 7.5",
  "US 8",
  "US 8.5",
  "US 9",
  "US 9.5",
  "US 10",
  "US 10.5",
  "US 11",
  "US 11.5",
  "US 12",
  "US 12.5",
  "US 13",
  "US 14",
  "US 15",

  // UK sizes
  "UK 3",
  "UK 3.5",
  "UK 4",
  "UK 4.5",
  "UK 5",
  "UK 5.5",
  "UK 6",
  "UK 6.5",
  "UK 7",
  "UK 7.5",
  "UK 8",
  "UK 8.5",
  "UK 9",
  "UK 9.5",
  "UK 10",
  "UK 10.5",
  "UK 11",
  "UK 12",
  "UK 13",
  "UK 14",

  // EU sizes
  "EU 35",
  "EU 35.5",
  "EU 36",
  "EU 36.5",
  "EU 37",
  "EU 37.5",
  "EU 38",
  "EU 38.5",
  "EU 39",
  "EU 39.5",
  "EU 40",
  "EU 40.5",
  "EU 41",
  "EU 42",
  "EU 42.5",
  "EU 43",
  "EU 44",
  "EU 45",
  "EU 45.5",
  "EU 46",
  "EU 47",

  // International / universal sizes
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "XXXL",
  "One Size",
  "Adjustable",
  "Custom",
];

// --------------------
// Clothing Sizes
// --------------------
const clothSizes: string[] = [
  // US sizes
  "US 0",
  "US 1",
  "US 2",
  "US 3",
  "US 4",
  "US 5",
  "US 6",
  "US 7",
  "US 8",
  "US 9",
  "US 10",
  "US 11",
  "US 12",
  "US 13",
  "US 14",
  "US 15",
  "US 16",
  "US 18",
  "US 20",
  "US 22",
  "US 24",
  "US 32",
  "US 34",
  "US 36",
  "US 38",
  "US 40",
  "US 42",
  "US 44",
  "US 46",
  "US 48",

  // UK sizes
  "UK 2",
  "UK 4",
  "UK 6",
  "UK 8",
  "UK 10",
  "UK 12",
  "UK 14",
  "UK 16",
  "UK 18",
  "UK 20",
  "UK 22",
  "UK 24",
  "UK 26",
  "UK 34",
  "UK 36",
  "UK 38",
  "UK 40",
  "UK 42",
  "UK 44",
  "UK 46",

  // EU sizes
  "EU 32",
  "EU 34",
  "EU 36",
  "EU 38",
  "EU 40",
  "EU 42",
  "EU 44",
  "EU 46",
  "EU 48",
  "EU 50",
  "EU 52",
  "EU 54",
  "EU 56",

  // International / universal sizes
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "XXXL",
  "One Size",
  "Petite",
  "Plus Size",
  "Tall",
  "Short",
  "Custom",
];
// --------------------
// Size Property Templates
// --------------------
const shoeSizeProperty = {
  name: "Size",
  type: "enum" as const,
  enumValues: shoeSizes,
  required: true,
  filterable: true,
  order: 3,
};

const clothSizeProperty = {
  name: "Size",
  type: "enum" as const,
  enumValues: clothSizes,
  required: true,
  filterable: true,
  order: 3,
};

const babyClothSizeEnums = [
  "NB", // Newborn
  "0-3M",
  "3-6M",
  "6-9M",
  "9-12M",
  "12-18M",
  "18-24M",
  "2T",
  "3T",
  "4T",
  "5T",
];
const kidsClothSizeEnums = [
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
];
const babyShoeSizeEnums = [
  "UK 0",
  "UK 1",
  "UK 2",
  "UK 3",
  "UK 4",
  "US 1",
  "US 2",
  "US 3",
  "US 4",
  "US 5",
  "EU 16",
  "EU 17",
  "EU 18",
  "EU 19",
  "EU 20",
];
const kidsShoeSizeEnums = [
  "UK 5",
  "UK 6",
  "UK 7",
  "UK 8",
  "UK 9",
  "UK 10",
  "UK 11",
  "UK 12",
  "UK 13",
  "US 5",
  "US 6",
  "US 7",
  "US 8",
  "US 9",
  "US 10",
  "US 11",
  "US 12",
  "US 13",
  "EU 28",
  "EU 29",
  "EU 30",
  "EU 31",
  "EU 32",
  "EU 33",
  "EU 34",
  "EU 35",
];

const hairTypeEnums = [
  "Straight",
  "Wavy",
  "Curly",
  "Coily",
  "Kinky",
  "Relaxed",
  "Braided",
  "Dreadlocks",
  "Extensions",
  "Weaves",
  "Natural",
  "Chemically Treated",
  "Colored",
  "Ombre",
];

const skinTypeEnums = [
  "Normal",
  "Dry",
  "Oily",
  "Combination",
  "Sensitive",
  "Acne-prone",
  "All Skin Types",
];

const skinConcernEnums = [
  "Acne",
  "Dark Spots",
  "Hyperpigmentation",
  "Fine Lines",
  "Wrinkles",
  "Dullness",
  "Uneven Texture",
  "Redness",
  "Pores",
  "Dryness",
  "Oil Control",
];
const hairConcernEnums = [
  "Dryness",
  "Breakage",
  "Hair Loss",
  "Dandruff",
  "Frizz",
  "Split Ends",
  "Thinning",
  "Scalp Care",
  "Damage Repair",
];

const productFormEnums = [
  "Cream",
  "Lotion",
  "Oil",
  "Serum",
  "Gel",
  "Foam",
  "Butter",
  "Spray",
  "Stick",
  "Powder",
  "Mask",
  "Electronic",
  "Metal"
];
const hairMaterialEnums = [
  "Human Hair",
  "Synthetic Hair",
  "Heat Resistant Synthetic",
  "Blended Hair",
  "Remy Hair",
  "Virgin Hair",
  "Processed Hair",
];
const storageCapacityEnumValues = [
  "16MB",
  "32MB",
  "64MB",
  "128MB",
  "256MB",
  "512MB",
  "1GB",
  "2GB",
  "4GB",
  "8GB",
  "16GB",
  "32GB",
  "64GB",
  "128GB",
  "256GB",
  "512GB",
  "1TB",
];
const ramEnumValues = [
  "8MB",
  "32MB",
  "64MB",
  "128MB",
  "256MB",
  "384MB",
  "512MB",
  "1GB",
  "2GB",
  "3GB",
  "4GB",
  "6GB",
  "8GB",
  "12GB",
  "16GB",
];
const networkTypeEnumValues = ["2G", "3G", "4G LTE", "5G", "Wi-Fi Only"];

const simTypeEnumValues = ["Single SIM", "Dual SIM", "eSIM", "Dual SIM + eSIM"];

const batteryCapacityEnumValues = [
  "Under 2000 mAh",
  "2000–2999 mAh",
  "3000–3999 mAh",
  "4000–4999 mAh",
  "5000 mAh & Above",
];

const chargingTypeEnumValues = [
  "USB-C",
  "Lightning",
  "Micro-USB",
  "Wireless Charging",
];

const audioConnectivityEnumValues = ["Wired", "Bluetooth", "Wired & Bluetooth"];
const noiseCancellationEnumValues = [
  "None",
  "Passive",
  "Active Noise Cancellation (ANC)",
];

const watchSizeEnumValues = [
  "38mm",
  "40mm",
  "41mm",
  "42mm",
  "44mm",
  "45mm",
  "49mm",
];

const watchOSEnumValues = ["watchOS", "Wear OS", "Proprietary OS"];

const cableLengthEnums = ["0.25m", "0.5m", "1m", "1.5m", "2m", "3m"];
const lightTypeEnums = [
  "LED",
  "RGB",
  "Dimmable LED",
  "Bi-Color LED (Warm/Cool)",
];

const wattageEnums = [
  "5W",
  "10W",
  "12W",
  "15W",
  "18W",
  "20W",
  "24W",
  "30W",
  "36W",
  "45W",
  "60W+",
];
const processorEnums = [
  "Intel Core i3",
  "Intel Core i5",
  "Intel Core i7",
  "Intel Core i9",
  "AMD Ryzen 3",
  "AMD Ryzen 5",
  "AMD Ryzen 7",
  "AMD Ryzen 9",
  "Apple M1",
  "Apple M2",
  "Apple M3",
  "Other",
];
const screenSizeEnums = [
  "11 inch",
  "13 inch",
  "14 inch",
  "15 inch",
  "16 inch",
  "17 inch",
  "19 inch",
  "21 inch",
  "24 inch",
  "27 inch",
  "32 inch+",
];
const connectivityEnums = [
  "USB",
  "USB-C",
  "Bluetooth",
  "Wi-Fi",
  "HDMI",
  "Wireless",
  "Wired",
];
const printerTypeEnums = ["Inkjet", "Laser", "Thermal", "All-in-One"];
const productStatusEnums = ["draft", "under_review", "live", "rejected"];
const occasionEnums = [
  "Athletic",
  "Autumn",
  "Ballet",
  "Beach",
  "Boho",
  "Bridal",
  "Bridal Shower",
  "Bride",
  "Bridesmaid",
  "Business",
  "Camping",
  "Casual",
  "Chic",
  "Cocktail",
  "Corporate",
  "Cruise",
  "Cultural",
  "Cycling",
  "Dance",
  "Day",
  "Date",
  "Dressy",
  "Evening",
  "Fall",
  "Festive",
  "Fitness",
  "Formal",
  "Funeral",
  "Gala",
  "Gym",
  "Gymnastics",
  "Groom",
  "Groomsman",
  "Hiking",
  "Holiday",
  "Horse Riding",
  "Maternity",
  "Office",
  "Other",
  "Outdoor",
  "Party",
  "Pilates",
  "Retro",
  "Resort",
  "Running",
  "Scootering",
  "Sexy",
  "Skateboarding",
  "Skating",
  "Skiing",
  "Smart Casual",
  "Spring",
  "Sports",
  "Summer",
  "Surfing",
  "Swimming",
  "Travel",
  "Vacation",
  "Walking",
  "Wedding",
  "Winter",
  "Work",
];

const fitEnums = [
  "Regular",
  "Slim",
  "Skinny",
  "Straight",
  "Bootcut",
  "Flare",
  "Wide-Leg",
  "Cropped",
  "Culotte",
  "Palazzo",
  "Paperbag",
  "Pegged",
  "Tapered",
  "Carrot",
  "Boyfriend",
  "Mom",
  "Dad",
  "High-Waist",
  "Low-Waist",
  "Mid-Waist",
  "Drop-Waist",
  "Plus-Size",
  "Petite",
  "Maternity",
  "Tall",
  "Short",
  "Long",
  "Oversized",
  "Fitted",
  "Relaxed",
  "Baggy",
  "Slouchy",
  "Boxy",
  "Flowy",
  "Draped",
  "Tailored",
  "Other",
];
export {
  currencyEnums,
  MaterialProperty,
  PatternProperty,
  colorPropertyObj,
  conditionPropertyObject,
  shoeSizes,
  clothSizes,
  shoeSizeProperty,
  clothSizeProperty,
  conditionEnumValues,
  colorEnums,
  patternEnums,
  materialEnums,
  accessorySizeEnums,
  babyClothSizeEnums,
  babyShoeSizeEnums,
  kidsClothSizeEnums,
  kidsShoeSizeEnums,
  hairTypeEnums,
  skinTypeEnums,
  skinConcernEnums,
  hairConcernEnums,
  productFormEnums,
  hairMaterialEnums,
  storageCapacityEnumValues,
  ramEnumValues,
  networkTypeEnumValues,
  simTypeEnumValues,
  batteryCapacityEnumValues,
  chargingTypeEnumValues,
  audioConnectivityEnumValues,
  noiseCancellationEnumValues,
  watchSizeEnumValues,
  watchOSEnumValues,
  cableLengthEnums,
  lightTypeEnums,
  wattageEnums,
  processorEnums,
  screenSizeEnums,
  connectivityEnums,
  printerTypeEnums,
  productStatusEnums,
  occasionEnums,
  fitEnums,
};
